### ISSUE TITLE
memory increase

### ISSUE THREAD

**Issue by loudoweb** [jcward/hxtelemetry#22]
I found memory increase in my app when using hxScout.
I believed that was a memory leak in my app but when I open my app without hxScout I do not have memory increase. I guess memory increase in hxScout is ok since it collects data all the time but why the memory used by my app is also increasing?

**Comment by jcward** [comment]
Hi, can you describe your steps and when memory increased?  For example, I know one case where a memory problem occurs:

1) open hxScout
2) open app under test (AUT)
3) close hxScout

If AUT doesn't crash, it begins collecting lots of memory, because the stats are being collected but no longer being flushed to hxScout. Also, if hxScout becomes paused or is too slow to keep up with AUT, you could perhaps get the same situation.

Can you determine (from the timestamps in hxScout) if hxScout is keeping up with the AUT? Is hxScout showing low framerate?

**Comment by loudoweb** [comment]
I will try to collect more information about this as soon as I can.

**Comment by jcward** [comment]
Uh oh, I think you might be right. I'll investigate further. Maybe the stats aren't being released properly, when while it's still running.

**Comment by jcward** [comment]
I've submitted a PR to hxcpp: https://github.com/HaxeFoundation/hxcpp/pull/272

You can access this fix now by grabbing [my Debug.cpp](https://raw.githubusercontent.com/jcward/hxcpp/telemetry_fix/src/hx/Debug.cpp) file and placing it in your `hxcpp/src/hx` folder. 

That's for telemetry stats not being deleted properly. There's another fix in this hxtelemetry repo for the "memory collects after disconnecting" problem, pushing now.

Thanks!

**Comment by loudoweb** [comment]
Thanks. I'll tell you if I get more info on this.

**Comment by jcward** [comment]
FYI: This PR was merged into HaxeFoundation/hxcpp in git last night, and a nightly hxcpp build is available from: http://www.openfl.org/builds/hxcpp/hxcpp-3.1.39-432-g3845ba8.zip

Thanks again, Ludovic!

**Comment by loudoweb** [comment]
no problem. Thank you.
